spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/Documents/java-workspace/my-project/database-files/my-own-test
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
