spring:
  application:
    name: auth-service
  datasource:
#    url: jdbc:h2:tcp://localhost/~/Documents/java-workspace/my-project/database-files/my-own-test
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 19095

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

jwt:
  access-expiration: 3600000
  secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"