spring:
  application:
    name: server

server:
  port: 19090

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://localhost:19090/eureka/
  instance:
    hostname: localhost
